openstack/tools/configure_octavia.sh

Starting with Wallaby, Octavia insists on a system scoped token for
the admin user [1]. Instead, this change adds the `load-balancer_admin`
role to the `admin` user.
[1] https://docs.openstack.org/octavia/wallaby/configuration/policy.html

Add `load-balancer_admin` role to `admin` user

---

openstack/pipeline/02configure

Adding this switch since this configuration is
not supported for versions prior to Victoria.
Closes #22

Octavia OVN provider only works after Ussuri

---

openstack/tools/enable_samltestid.sh

This tool was using role "Member" which does not
exist in our current default setup and should actually
use "member".

Fix keystone-saml setup tool

---

common/generate-bundle.sh
common/render.d/all
overlays/grafana.yaml

The osm and lma charms each have their own version of
the grafana charm where the lma one has no prefix in
the charmhub.
Resolves: #30

Skip prefix for non-osm grafana

---

common/ch_channel_map/bionic
common/ch_channel_map/focal
common/ch_channel_map/focal-wallaby
common/ch_channel_map/focal-xena
common/ch_channel_map/impish
common/ch_channel_map/jammy
common/ch_channel_map/xenial
common/charm_lists

This change aims to add the correct channel for barbican-vault
Closes: #54
Signed-off-by: David Negreira <david.negreira@canonical.com>

Fix channel for barbican-vault

---

openstack/novarc

When the keystone application doesn't have set admin-password
configuration key, a random password is generated and stored in the
leader databag. This change reads the password from the leader if the
config is not set.
Details on how the keystone charm stores the admin password can be found
at https://opendev.org/openstack/charm-keystone/src/branch/master/hooks/keystone_utils.py#L1480

Read keystone password from leader if not set in config.

---

.github/workflows/lint.yaml
openstack/novarc

Also lint `novarc`

---

openstack/tools/instance_launch.sh

This change adds a `--network` command line option to the
`instance_launch.sh` script. This option enables the use of networks
other than the default `private` network.

[TOOLS] Add `--network` command line option

---

overlays/mysql-innodb-cluster.yaml
overlays/mysql.yaml

Tell MySQL not to call sync for each individual database write, it will
still do so about once per second.
This adds a high load to the underlying storage which is slow in
stsstack, and, is only required to ensure we don't lose data in a crash.
This helps speed up all of the initial database migrations quite a bit
and will also lower the disk load on stsstack as a whole.
Since these are testing environments, it doesn't really matter, also
with openstack the one second or so of writes in the event of a
crash/poweroff are typically important - just status updates, etc.
Additionally in multi-node setups (e.g. mysql-ha or always in the case
of mysql-innodb-cluster) the write is done to all 3 nodes anyway and is
still kept if one node crashes or is powered off before the others.
I have used …

mysql: Set tuning-level=fast

---

openstack/tools/juju-lnav
tools/juju-lnav

The `juju-lnav` script is a helper script to call `lnav` (needs to be installed
via package or snap) on multiple machines, applications, or units. For example,
$ ./tools/juju-lnav octavia:/var/log/octavia/*.log{,1}
Will open the current and the first rotated log files from all of the `octavia`
units.
Likewise
$ ./tools/juju-lnav octavia:/var/log/octavia/*.log \
nova-cloud-controller:/var/log/nova/*.log
Will load the logs on all `octavia` and all `nova-cloud-controller` units.
For more information on how to use `lnav` please visit lnav.org.

Add script to look at logs from multiple units

---

tools/lint-git-messages.sh

The command wc --chars <<<${subject} does not work right as it always counts one extra char. For example:
$ wc --chars <<<""
1
$ wc --chars <<<"12345678901234567890123456789012345678901234567890" 
51

Fix error counting length of the commit subject

---

common/generate_bundle_base
common/helpers

When using maas it is mandatory to set a default
binding that exists (see LP #1994124).

Ensure default binding provided with maas

---

openstack/openstack.yaml.template
overlays/cinder-lvm.yaml
overlays/cinder-purestorage.yaml
overlays/cinder-volume.yaml

Move LVM configuration from cinder to cinder-lvm charm
Use storage spaces to allocate storage for cinder-lvm
Use lioadm for cinder-lvm (bug workaround)
Use cinder-volume:identity-credentials by default

Cinder Improvements

---

common/ch_channel_map/jammy-zed
openstack/openstack.yaml.template
openstack/pipeline/02configure
overlays/mysql-innodb-cluster.yaml
overlays/rabbitmq-source.yaml

Add jammy-zed support by specifying the zed-specific 22.09 OVN release

Add jammy-zed support (OVN 22.09)

---

openstack/pipeline/02configure
overlays/cinder-lvm-wallaby.yaml
overlays/cinder-lvm.yaml

The target_helper lioadm was only introduced as default in wallaby. So, older versions don't have it. See
https://bugs.launchpad.net/charm-cinder-lvm/+bug/1949074 for more info

Fix target helper for victoria series

---

overlays/k8s-vault-lb.yaml

Seems that the `kubernetes-control-plane` requires the `vault-kv` -> `vault:secrets` relation in order to configure the VIP IP of the vault and be able to connect to it properly.

add missing vault-kv relation to kubernetes-control-plane

---

tools/lint-git-messages.sh

The body line width detector was using the '>' comparison which is meant
for strings, not integers. In practice it was failing on a 9 character
wide line.
Switch to the correct "-gt" integer check.

lint-git-messages.sh: Fix line width detection

---

overlays/k8s-ceph.yaml

ceph-storage relation was deprecated on 1.24[1], so remove it.
Fixes #41
[1] https://ubuntu.com/kubernetes/docs/upgrade-notes#ceph-storage-relation-deprecated

Remove deprecated Kubernetes relation with Ceph

---

common/ch_channel_map/any_series
common/ch_channel_map/lunar
common/helpers
common/openstack_release_info
common/render.d/all

Due to some checks being done by alphabetical order, it would break how we would assign and ensure that minimal versions of certain charms are installed in certain openstack versions.
How I approach the fix is by putting all the relevant openstack versions in an ordered array so that we can compare numerically the openstack versions between eachother.
Closes: #112

Add lunar/antelope support

---

.github/workflows/lint.yaml
openstack/tools/create-microceph-vm.sh

This script will deploy microceph inside 3 LXD containers. By default the containers are named `microceph-{1,2,3}`. Ceph can be used via the microceph.ceph command, e.g.
lxc exec microceph-1 -- microceph.ceph status
The script can also be run inside a VM. For example, using juju the following deploys microceph inside a VM:
juju add-model microceph
juju deploy --constraints mem=16G --series jammy ubuntu microceph-vm
juju ssh microceph-vm/0 -- sudo usermod --append --groups lxd ubuntu
juju ssh microceph-vm/0 -- lxd init --auto
juju scp openstack/tools/create-microceph-vm.sh microceph-vm/1:
juju ssh microceph-vm/0 -- ./create-microceph-vm.sh
After everything is deployed, ceph can be used via the microceph.ceph command, e.g.
juju ssh microceph-vm/0 -- microceph.ceph status

Add script to deploy microceph via LXD

---

common/openstack_release_info

This is necessary due to minimum release requirements for designate.
Closes: #114

Add ocata to openstack_release_info

---

common/ch_channel_map/bionic
common/ch_channel_map/jammy

The mysql-router charm will not relate the shared-db relation on edge.

Switch to stable channel for bionic and jammy

---

common/helpers

Charmhub charms (including git master) now set the charm default
openstack-origin/source option to the matching openstack release name
(e.g. 'wallaby') instead of the previous default of 'distro'.
As a result, if you try to test a git master charm against an older
OpenStack release that uses distro (e.g. ussuri) you will accidentally
upgrade that charm from the current release (e.g. focal-ussuri) to the
latest release in git master (e.g. focal-wallaby).
While this is not technically supported and some charms are now removing
support for older releases from git master, it's still OK to test some
charms like this and even if not supported it usually incorrectly
upgrades that application which breaks the environment and is difficult
to rollback leaving you having to spend another 30-60+ …

Explcitily specify source=distro instead of blank

---

common/openstack_release_info

List of openstack release names must include all releases (even eol) in order to be able to match gt/ge/lt for any release.
Resolves: #118

Fix --telemetry

---

doc/openstack/bgp.md

The neutronclient is deprecated, so update the BGP examples to use the openstackclient.
Trivialfix

Change the BGP examples to use the openstackclient

---

common/ch_channel_map/bionic

OVN and Rabbitmq charm channels needed adjusting
to use versions that support Bionic.
Closes-Bug: #131

Update bionic versions

---

openstack/pipeline/02configure

Don't use vault certificates by default with MySQL InnoDB Cluster.
The certificates aren't setup until you unlock the vault, which you
can't do until halfway through the charm deployment after MySQL has
already started since vault itself depends on MySQL.
When you unlock it, the certificates are created and the MySQL charm
then reconfigures and restarts MySQL which causes any OpenStack service
that is doing database migration/setup to fail and error out
permanently.
In my experience, this happens most of the time in practice.
We're not normally using this for real deployments, so add the
--mysql-innodb-cluster-ssl option to opt-in instead.

mysql-innodb-cluster: no SSL by default

---

openstack/novarc

When keystone unit 0 is missing or another unit is the current leader,
the hard-coded reference to `keystone/0` will yield a null or incorrect
result.

Remove hard-coded unit reference

---

openstack/pipeline/02configure
openstack/tools/create_octavia_lb.sh

This change enables the ovn-provider for Octavia mandatory if at least
Victoria and OVN.

Make ovn provider non-optional

---

openstack/openstack.yaml.template
tools/juju-bundle-applications.py

To adjust to new juju 3.2 behaviour that does not
allow relations referencing overlay applications
in the base bundle.
Ref: https://bugs.launchpad.net/juju/+bug/2041785
Resolves: #149

Separate relations into separate yaml document

---

common/helpers

OS releases need to be compared using the `os_releases` associative
array. This change fixes the incorrect comparison for mapping to the
appropriate Ceph release.
Fixes: https://github.com/canonical/stsstack-bundles/issues/162

Compare OS release correctly

---

openstack/tools/instance_launch.sh

This script presumes that the model's `novarc` file was sourced. Let's
source it explicitly just in case.

Source env file

---

openstack/tools/instance_launch.sh

It incorrectly says to use ~/testkey.pem when it should be ~/testkey.priv.
TrivialFix

Fix testkey hint in instance_launch.sh

---

common/helpers

The `systemd-resolve` tool has been renamed to `resolvectl` in [systemd 239](https://github.com/systemd/systemd/blob/main/NEWS#L8539). 
From Jammy onwards the symlink `systemd-resolve` has been deleted and this code does not work.
Focal has systemd 245 so this change in fact removes support for Bionic and adds support for Jammy and following releases. If support for Bionic is still desired the patch should be expanded.

Change systemd-resolve for resolvectl

---

kafka/tools/create_volumes.sh

This script creates two volumes for each kafka unit and attaches them to the units.

Add script to create volumes needed by kafka units

---

kubernetes/kubernetes.yaml.template

The Kubernetes version (the snap) is pinned to the charm channel so we can move the `channel` option to the charm level.

Move the channel option to the charm

---

jaas/pipeline/02configure

Previously it didn't work for juju versions greater that 3.2

Fix juju version check

---

openstack/pipeline/02configure

Gnocchi was adding the ceph overlay file when it should have been setting the config opt to allow the standard handler to do its thing. This ensures that all the required parts are performed such as configuring juju storage.

Fix Gnocchi ceph dependency

---

common/generate_bundle_base

On STSStack, the first call to `openstack subnets` is expected to fail.
The script needs to ignore this failure.

Ignore errors when listing subnets

---

openstack/profiles/prodstack6

Since the allocations changed on prodstack6 to /25 we need to adapt the ./configure script to be more smart about which subnets we need to allocate to the FIP pool.

fix FIP allocation on prodstack6

---

openstack/pipeline/02configure

This is to ensure that any overlays that depend on it get to use it since they will execute in any order.

Ensure vault set as early as possible when ml2-ovn used

---

openstack/module_defaults
openstack/pipeline/02configure

On PS6 we get a flavor with a disk of 20G if we do not constrain the
root-disk. This will break launching a jammy server for example because
it requires a 20G disk.

Add root-disk constraint to nova-compute

---

common/generate_bundle_base

At the moment the VIPs start from 106, even though the ip range may start from 129.
We use `ipcalc` command to find the HostMin, and calculate cased on that

Fix prodstack6 VIP allocation

---

common/generate_bundle_base
openstack/tools/allocate_vips.sh

This eneusres that these IP addresses don't get used by OpenStack and the relevant VIPs can be utilised and hence don't have conflicts

Add a script to allocate VIPs in PS6

---

openstack/profiles/default

This is to allow octavia-diskimage-retrofit to work without having to provide any args our source-image id since it will look for the image corresponding to the release of openstack deployed (using image
properties).

Add focal image to glance for openstack

---

openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/identify_charm_func_tests.py

Also includes tool to identify func test targets from the charm.

Add openstack charm func test runner

---

openstack/tools/charmed_openstack_functest_runner.sh

Don't enable debug by default so that output does not contain sensitive information.

Add --debug flag

---

jaas/configure
openstack/configure

These two scripts still used Sh shell in shebang. In some situations, it was an issue when they sourced Bash specific scripts (directly or indirectly)
See PR #208 for details

Replace Sh shell in shebang with Bash

---

openstack/tools/charmed_openstack_functest_runner.sh

The list of test targets was always "target" instead of the actual list
of targets due to an accidentally ommited $-sign in #230

charm func test runner: fix broken target list

---

common/generate_bundle_base
openstack/tools/allocate_vips.sh
openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/create_ipv4_octavia.sh
openstack/tools/create_nova_az_aggregates.sh
openstack/tools/create_octavia_lb.sh
openstack/tools/create_sg_log.sh
openstack/tools/delete_project.sh
openstack/tools/enable_samltestid.sh
openstack/tools/float_all.sh
openstack/tools/install_local_ca.sh
openstack/tools/instance_launch.sh
tools/stack-manager/mark-vms-managed.sh
tools/stack-manager/mark-vms-unmanaged.sh
tox.ini

Adds all bash files to bashate test and fixes errors.

Fix bashate tests

---

openstack/tools/charmed_openstack_functest_runner.sh

charm func test runner: default charmcraft_channel
The charmcraft channel defaults to 1.5/stable [1], some charms omit
it from osci.yaml [2] so we need to implement a default.
[1] https://github.com/openstack-charmers/zosci-config/blob/master/roles/charm-build/defaults/main.yaml
[2] https://github.com/openstack/charm-glance-simplestreams-sync/blob/stable/yoga/osci.yaml
Adding TEST_VIP0x for some charms ( e.g charm-mysql-router )
[1] https://github.com/search?q=repo%3Aopenstack-charmers%2Fzaza-openstack-tests+TEST_VIP00&type=code

default charmcraft_channel, TEST_VIP0X

---

openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/func_test_tools/manual_functests_runner.sh
tox.ini

- Add support for remote-build for when the tests need to be run from a container due to python version
- Add support for manual functest runners (deploy, configure, test) for when the full suite fails requiring more granular approach (such as a sleep)

charm test runner: manual_functest and remote-build

---

openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/func_test_tools/common.py
openstack/tools/func_test_tools/test_is_voting.py

If the target was not found in osci.yaml then osci will fallback to looking at
https://github.com/openstack-charmers/zosci-config/blob/master/zuul.d/project-templates.yaml

Support functest voting lookup fallback

---

common/generate_bundle_base
openstack/module_defaults
openstack/openstack.yaml.template
openstack/pipeline/02configure
overlays/openstack/vault-openstack-secrets.yaml

Always deploy an 'ephemeral' storage disk for nova-compute, even if we are not 
using vault. While vault is pulled in by OVN in the majority of currently used
OpenStack versions, this will ensure we always have one of that size
regardless.
Remove the increased root-disk=80G size for nova-compute units, since we can 
use the space from the ephemeral disk instead.
Set a default root-disk=20GB constraint. Previously the prodstack6 environment 
would give us 20GB root disks as that is set in the default flavors, however
when booting from volume with root-disk-source=volume this is ignored and a
juju default of 30GB is used. Switch this to 20GB to go back to the previous
amount of storage.
With these changes the size of a jammy-yoga deployment with Ceph and 3x 
nova-compute nodes is reduced …

Reduce storage requirements of a default deployment

---

.gitignore
openstack/tools/func_test_tools/test_is_voting.py

We need to support job defs that have not voting key which implies voting=True.
Also adds __pycache__ to .gitignore

Fix func target voting test

---

openstack/tools/func_test_tools/identify_charm_func_tests.py

Some tests.yaml files have bundles set to None so we need to protect against this.

Support tests.yaml bundles defined as None

---

common/helpers

The PR #228 [1] changed to use jq instead of sed to parse yaml when relocating two lines. However, yaml format is not supported in versions prior to juju 3.x.
$ juju show-cloud localhost --format json
ERROR invalid value "json" for option --format: unknown format "json"
Therefore, we need to revert back to the previous two lines to support both juju 2.x and juju 3.x simultaneously.
[1] https://github.com/canonical/stsstack-bundles/pull/228

The command 'juju show-cloud' does not support JSON format

---

openstack/tools/charmed_openstack_functest_runner.sh

Juju 2 prints output to stderr as opposed to stdout in Juju 3 so need to pipe both to logs.

Ensure func tests log both stdout and stderr

---

openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/openstack_regression_tests_runner.sh
tox.ini

Run the Openstack release tests from charmed-openstack-tests.

Add openstack regression test runner

---

openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/func_test_tools/common.sh
openstack/tools/openstack_regression_tests_runner.sh
tox.ini

Also moves some commmon code to new common.sh

Delete all zaza models before and after each test

---

openstack/tools/charmed_openstack_functest_runner.sh
openstack/tools/func_test_tools/common.py
openstack/tools/func_test_tools/extract_job_target.py
openstack/tools/func_test_tools/identify_charm_func_test_jobs.py
openstack/tools/func_test_tools/test_is_voting.py

We first need to identify jobs and maintain that list as-is since voting info uses job names. We then
de-reference jobs where needed at the last minute to extract e.g. aliased targets that use overlays.

Fix func test target name identification

---

openstack/tools/func_test_tools/common.py
openstack/tools/func_test_tools/identify_charm_func_test_jobs.py

tests/tests.yaml is actually ignored by osci and jobs are in fact determined from a combination of zosci-config and local osci.yaml.

More fix to how we identify branch jobs

---

openstack/tools/func_test_tools/identify_charm_func_test_jobs.py

.gitreview will not have a defaultbranch config
on master branch.

Func tests branch detection fallback

---

openstack/novarc

The OS_AUTH_PROTOCOL should be set to 'https' only when a relation of type 'certificates' exists between keystone and vault. Before it was set when the the vault charm was found in the deployment.

fix setting OS_AUTH_PROTOCOL to https

---

openstack/tools/create_octavia_lb.sh

This change adds the `--subnet-id` command line option to the member create function of Octavia in case the VIP and the member networks are not connected via a router.
The change also cleans up the script a bit.

Add member subnet option to script

---

doc/openstack/tutorial.md

The tutorial doc, which prints a message after
generate-bundle.sh is run, has ./configure as the
first step. But if you do that there is a complaint
that ./tools/vault-unseal-and-authorise.sh has not
been run yet. A similar message is printed if you
source novarc.
Move it to before ./configure since it must be
run first.

Move vault unseal before ./configure

---

overlays/openstack/octavia-diskimage-retrofit-glance.yaml

The current configuration uses only 1 core CPU, and to be able to convert the images it's necessary to have at least 4 cores.

Fixing the octavia-diskimage-retrofit

---

tools/cleanup-cinder-attachments.sh

The 'in-use' volumes, attached to non-existent servers, do not
necessarily have `juju` in their name. This change removes this
restriction.

Also remove volume that have different names

---

kubernetes/kubernetes.yaml.template

Tokens relation is needed so that the kubernetes worker can query metrics information from the kubelet

Adding the tokens relation

---

openstack/pipeline/02configure

Hyperconvereged mode needs at least 3 phyiscal machines to deploy so that applications with min 3 units have somewhere to go.
Resolves: #293

Use default 3 computes for hyperconveregd

---

openstack/profiles/default
openstack/tools/configure_octavia.sh
openstack/tools/upload_octavia_amphora_image.sh

The current implementation parallelizes the setting of image properties across the images and the properties. This can lead to some of the properties getting "lost" and not getting set. Missing image properties will break the octavia-diskimage-retrofit charm when one of those images is used as the base for the amphora image.
The `juju run` action has a `--wait` parameter which defaults to `0s` which really means 1 minute. On PS6 this timeout is too aggressive and the configure and retrofit actions time out.

Set image properties less aggressively

---

openstack/profiles/common

1GB is ideal for testing ubuntu images, 2GB was too much considering our compute VMs have only 4GB of RAM. This is essential when testing octavia because you need enough RAM for the user VM, the amphora, and the compute host to avoid crashes.
The xsmall flavor proposed is the same as the amphora size.

Add 1GB flavor for ubuntu images

---

overlays/openstack/neutron-ovn.yaml

Before caracal all false meant every node was
a gateway but caracal changed this and results
is no gateways until this is set to true.
See LP 2019217 for more info.

Set ovn prefer-chassis-as-gw=true

---

tools/juju-lnav

* Remove install_ssh_key
* Add check_ssh_key and exit if unable to connect
Previously juju-lnav attempted to copy the keys
`~/.ssh/id_rsa.pub` and `~/testkey.pub` to a server when connecting to a machine, if an initial ssh test failed. This could lead to confusing errors if either of the above keys was missing, and wouldn't necessarily fix connectivity issues. Also, lnav doesn't make it especially clear what's going on if it is unable to ssh.
This commit changes the script to bail out if it can't establish and ssh connection with the target machine, and instead prints instructions to the user letting them know they should add an ssh key to the server and try again.

Change juju-lnav to bail on failed ssh
