canonical/stsstack-bundles

- openstack/bin/add-data-ports.sh
> Remove unused data ports

- ceph/ceph.yaml.template
- ceph/pipeline/02configure
- openstack/openstack.yaml.template
- openstack/pipeline/02configure
- overlays/glance-ceph.yaml
- overlays/glance.yaml
- overlays/k8s-keystone.yaml
- swift/pipeline/02configure
- swift/swift.yaml.template
Allow Ceph to be deployed without any
Openstack components.
> [ceph] Add --no-openstack option

- tools/mongo-access.sh
Tested and I was able to access mongodb
> Add mongo access script

- tools/mongo-access.sh
Issue: canonical/stsstack-bundles#25
> Add command line options and help

- openstack/tools/enable_samltestid.sh
Add a check to the script to verify that the keystone-saml-mellon
application is deployed.
> Check for keystone-saml-mellon application

- .github/workflows/lint.yaml
- tools/model-poweroff.sh
- tools/model-poweron.sh
- tools/mongo-access.sh
> Add bashate linting to CI

- README.md
Issue: canonical/stsstack-bundles#51
> Add instructions on installing `openstackclients`

- openstack/module_defaults
- openstack/pipeline/02configure
- overlays/masakari-ha.yaml
- overlays/vault-openstack-certificates-masakari.yaml
* always configure vip for masakari
* add relation with vault if required
* configure maas settings in hacluster
> Fix masakari

- .github/workflows/lint.yaml
- openstack/novarc
- tools/lint-git-messages.sh
> Add git message linter

- tools/mongo-access.sh
> [TOOLS] Small cleanup

- openstack/profiles/default
Replaces bionic and focal for glance setup.
> Use Jammy as default image in glance

- tools/lint-git-messages.sh
> TOOLS: Also allow `TYPE:` subject lines

- .github/workflows/lint.yaml
- tools/juju-lnav
> Add more comments to the script

- tools/juju-lnav
> Fix the example in lnav script

- openstack/tools/instance_launch.sh
> Fix incorrect argument parsing

- common/render.d/all
Signed-off-by: Ponnuvel Palaniyappan <pponnuvel@gmail.com>
> Don't exit if there's no match for grep.

- common/generate_bundle_base
- tools/juju-bundle-applications.py
Improve the application list parsing using python+yaml in preparation
for further enhancements to the unit placement handling.
> Improve application list parsing

- openstack/tools/instance_launch.sh
> Relax --network syntax for instance creation

- openstack/tools/install_local_ca.sh
If you run novarc/install_local_ca.sh when vault is not yet initialised,
the previously invalid value of None was stored and causes future calls
to these scripts to error out.
While the script checked for this, after discovering the None it would
create a second temporary file in /tmp matching the "find" query and
when you call the script again in future in finds both files which
causes the script to error out.
There is not much point in using 'mktemp' to get a random path and then
trying to find it again using a unique part of the filename, so switch
to using a static path in /tmp which avoids having more than 1 match to
the path.
Secondly rather than check for the "None" error, more explicitly check
we get an actual SSL certificate back and if not, try to fetch the CA
again. Try to also …
> Handle previously invalid vault CA

- common/ch_channel_map/focal
> Update channel mappings for Focal/Ussuri

- common/ch_channel_map/bionic
- common/ch_channel_map/focal
- common/ch_channel_map/jammy
> add mongodb channels

- openstack/pipeline/02configure
Closes: https://github.com/canonical/stsstack-bundles/issues/121
> Default to OVN for release >= Ussuri

- common/helpers
> Switch default series to Jammy

- .github/workflows/lint.yaml
- common/ch_channel_map/any_series
- common/ch_channel_map/test-all.sh
- common/ch_channel_map/test-channel-map.sh
* Fix channel map for pacemaker-remote
* Fix testing script for channel maps
* Update bash linter
> Fix channel map for pacemaker-remote

- common/juju_helpers
- kubernetes/tools/configure_docker_registry.sh
- openstack/pipeline/02configure
- openstack/profiles/common
- openstack/profiles/default
- openstack/tools/configure_octavia.sh
- openstack/tools/enable_samltestid.sh
- openstack/tools/install_local_ca.sh
- tools/vault-unseal-and-authorise.sh
> juju 3.x support

- openstack/openstack.yaml.template
> Remove unecessary quotes

- common/charm_lists
- openstack/pipeline/02configure
- overlays/ceph/ceph-dashboard.yaml
Closes: canonical/stsstack-bundles#148
> Add ceph-dashboard option

- openstack/profiles/common
- openstack/profiles/prodstack6
- openstack/profiles/serverstack
- openstack/profiles/stsstack
Closes: https://github.com/canonical/stsstack-bundles/issues/166
> Add `UNDERCLOD_NETWORK_NAME` to all profiles

- jaas/configure
- jaas/jaas.yaml.template
- jaas/pipeline/00setup
- jaas/pipeline/02configure
- ssl/create_ca_cert_jaas.sh
The script finishes the configuration after the model has been deployed
> Add a configure script to JAAS

- kubernetes/pipeline/02configure
- overlays/kubernetes/k8s-lb.yaml
- overlays/kubernetes/k8s-openstack-cloud-controller.yaml
- overlays/kubernetes/k8s-openstack-integrator.yaml
Bring k8s deployment up to date with relationships and integrations
Closes: #186
> Fix k8s deployment

- doc/openstack/tutorial.md
- openstack/bin/add-data-ports.sh
- openstack/tools/sec_groups.sh
Includes some helpful comments in the related scripts to clarify a couple of overcloud vs undercloud questions.
Fixes #178
> Add tutorial to deploy openstack on serverstack

- common/generate_bundle_base
- common/helpers
Depending on which cloud we are deploying in this need a different default so this adds support for stsstack and prodstack.
> Dynamically set VIP_ADDR_START

- openstack/pipeline/02configure
- overlays/openstack/vault-manila-ganesha.yaml
This relation is needed as confirmed by Alex Kavanagh in 
https://bugs.launchpad.net/charm-manila-ganesha/+bug/2064487/comments/2
> Add relation between manila-ganesha and vault

- openstack/tools/enable_samltestid.sh
> Improve SAML configuration and handle HTTPS

- openstack/novarc
- openstack/novarcv3_domain
- openstack/tools/create_ipv4_octavia.sh
- openstack/tools/setup_tempest.sh
juju run now maps to run-action and we need to use juju exec for 3.5.
> Fix use of juju run

- openstack/tools/charmed_openstack_functest_runner.sh
- openstack/tools/func_test_tools/manual_functests_runner.sh
changes marked for followup patch
> Supplementary changes to remote build patch

- openstack/tools/charmed_openstack_functest_runner.sh
- openstack/tools/func_test_tools/common.py
- openstack/tools/func_test_tools/identify_charm_func_tests.py
Some charms define overlays in tests.yaml that map to a job in osci.yaml.
> Support func test zaza overlays

- openstack/tools/openstack_regression_tests_runner.sh
nova-compute needs enough resources to be able to create whatever vms the tests need so needs a flavor big enough to support that.
> Add support for release test bump constraints

- tools/juju-lnav
> Also install testkey for lnav

- openstack/pipeline/00setup
- openstack/pipeline/02configure
Need to unseal vault before configure script it run.
> Fix order of Openstack post-deploy actions

- common/helpers
Quick update to the `--default-binding` helper and closes #173 that I opened sometime ago
> Update default-binding helper

- docs/user-docs/guides/index.rst
> Fix spelling (again)

- common/helpers
- common/openstack_release_info
> Map numerical OpenStack release to names

- openstack/pipeline/02configure
- openstack/tools/upload_octavia_amphora_image.sh
- Add Juju version check and use appropriate command for upload.
- Update commit message to reflect the changes.
> Update Octavia amphora image upload script for different Juju versions.
